### ISSUE TITLE
Error on if[]

### ISSUE THREAD

**Issue by ToeiRei** [loewexy/pdns-acme#2]
`if [ $HANDLER = deploy_challenge ]` throws an error.
Guess it should be `if [[ $HANDLER = "deploy_challenge" ]]` 

same for `elif [[ $HANDLER = "clean_challenge" ]]` and `elif [[ $HANDLER = "deploy_cert" ]]`

**Comment by loewexy** [comment]
Which error do you get? I think it should work that way it is implemented, but i could be mistaken.

**Comment by ToeiRei** [comment]
`/pdns-acme: line 133: [: =: unary operator expected`

That message 3 times - line numbers exactly for the three candidates pointed out above.

**Comment by ToeiRei** [comment]
Could be that I'm running a pretty recent version of bash...

```
dns@pdns-server ~/ $ bash --version
GNU bash, version 4.3.48(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

```

**Comment by loewexy** [comment]
Maybe the missing Quotes around $HANDLER are the problem here. Can you try to replace $HANDLER with "$HANDLER" and see if this works?

Does your suggested fix work for you?

**Comment by ToeiRei** [comment]
the quotes also do the trick.

**Comment by loewexy** [comment]
Ok I would prefer that solution as it is more portable to other shells. I will post a fix to the master branch.

**Comment by ToeiRei** [comment]
Just wondering... I'm used to protect variables like  "${d}" to prevent modifications from outer script...
